{% set name = "psy-simple" %}
{% set version = "1.3.1" %}
{% set sha256 = "7251d3812aecc803f783a8bf754ddee9c2fbcb5efc100a97cc7d494eb0a928c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed -vvv
  skip: true  # [py < 37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - matplotlib-base >=2.0
    - {{ pin_compatible('psyplot', max_pin='x.x') }}

test:
  imports:
    - psy_simple

about:
  home: https://github.com/psyplot/psy-simple
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for simple visualization tasks

  description: |
    This psyplot plugin provides plot methods for simple visualization tasks
    like 2D plots, line plots, bar plots, etc.
  doc_url: http://psyplot.readthedocs.io/projects/psy-simple
  dev_url: https://github.com/psyplot/psy-simple

extra:
  recipe-maintainers:
    - Chilipp
