{% set name = "psy-simple" %}
{% set version = "1.5.1" %}
{% set sha256 = "52d39d79fe11f04d5e47736ab626497f53e5f9c611e6287157dff3d37887b1dd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - versioneer
    - tomli
  run:
    - python
    - matplotlib-base >=2.0
    - {{ pin_compatible('psyplot', max_pin='x.x', lower_bound='1.5.0') }}

test:
  imports:
    - psy_simple
    - psy_simple.plotters

about:
  home: https://codebase.helmholtz.cloud/psyplot/psy-simple
  license: LGPL-3.0-only
  license_family: GPL
  license_file:
    - LICENSES/
  summary: Psyplot plugin for simple visualization tasks

  description: |
    This psyplot plugin provides plot methods for simple visualization tasks
    like 2D plots, line plots, bar plots, etc.
  doc_url: http://psyplot.github.io/psy-simple
  dev_url: https://codebase.helmholtz.cloud/psyplot/psy-simple

extra:
  recipe-maintainers:
    - Chilipp
