{% set name = "psy-simple" %}
{% set version = "1.1.0" %}
{% set sha256 = "f1718e08b3301df1e82318335a673af40b2e078c6eda5911defb2417c798eb99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
  - python
  - setuptools
  run:
  - python
  - psyplot

test:
  imports:
  - psy_simple

about:
  home: https://github.com/Chilipp/psy-simple
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Psyplot plugin for simple visualization tasks

  description: |
    This psyplot plugin provides plot methods for simple visualization tasks
    like 2D plots, line plots, bar plots, etc.
  doc_url: http://psyplot.readthedocs.io/projects/psy-simple
  dev_url: https://github.com/Chilipp/psy-simple

extra:
  recipe-maintainers:
    - Chilipp
