appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: U+MQa4uqmuNRa0AMxU3I3oZM68yriY2PxiMezyN5aSJPiVpCIZdg2SBUvCBRiGJUbUCnDWrLTx6e2wmhCgBcpfHBatrzBtRRoZ8/ahbIEP5Mp6SR1rgBRZRslSW02ddt4OlpoB79Hs2ycRl6+PKXNrl71r9MEvKHA2BoMRTMLHKc1oTaM+0dI6BBLl/NIASr49hktkMqfP2Hn2zKFj/znY4gU+fTSe220G4rga3opBA+7PZqczOGoZda+o17Ngn7zzrJ3COIC0I4xXrJVqf0nbUn/MEXmft4Cr5ZmYCz7NILJhRFuXIB92pjK/KO35JjCuFvWdP0eEY7K+aGyrHonLX64C6xG37qK7eIVGImwgR0UCZ4Qqp5xq8BcifIMuDJepJj7pYM69RlP2zJtMppOcrXCIDWJ0NmCOQRz6AnbXZTQ39BWt15LzZcNLlS33PKtPXORl3yz1UgSgWzLgqnBNTPZ+cfKt0XK9O4AVdl70gNvuuWnhN2uypgAT2pX5q5NCPecVkav+j0rAwXaL02bL/BouEzMZ7ybluQSFGV9VafKfqY4IoUpCvYCvJ9m2vGJGH7NUn/8JGnV2jLqn5nk3inP4wC+cWp3vLI5dCJm+tkc6lUsnsKsYBkg8mSXKXU3f5hhklHuQgLmegID+PQ+sN7BjjHuQfctJNaZ6DLscU=}
