travis:
  secure:
    BINSTAR_TOKEN: FBPcHZAGRfTR94vU0joRs67EhMm5M55kVAwyOSpCeskYNnHw4lrL5clehXdDt2mlLfCaVXdKPbo4UhR8yw+kPSlSz78/8WWYNxa3XCLKWu/nMwEPdyCqXpZnKE1SiUYEl0fCff9XQz1nIXdnNFo0VI04bTTJrPU2qu+pf4bgDzUQsXe4kWSSIG6PnA3XwnW1scZ2GedXblXkwsBxa2Q6DWTPffiYE2Q4EFjWFJy44TLY6eZ0EnGX7lCT8w3z4cVMS/UxjzDmwHxnuhGLGP4VXlM3ieO+UbqlIxsi0SoOdR0KMFPnVHzhyFfbsOdSibNtaBI/KVVjREwBjgV4l8meQes31gfpVVwFLKAOdnf+RhggEZOiPeSFdNt0J2jW1XeLnFatItoZM1AM1cwPyKfbxw5vX4Nzuh38fxMBAwDMxiCyZky2TLCSQk1XevlWLjy6CadHJQvotgXDV/3J3t9RDR9sq5tSYNEoyIEO1ugxKai10S+RHa90QDEnR5O8WgOhFrOTCEWr+yWD18w+u0uS6wRtgF7MgPI9RvNxR7ggahZ4JMwB+f/uxhMgQNrmJrRY6Y5h78Y0GGjOBPQs3eyH1WbC2dKiZujGfCzYIG42nzGcUDkpKIs5ExjUP3/CF8m66b5wJo7ulI1srvv3Fw8XnaTHz63mBksyEG11cvW7RgE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
