travis:
  secure:
    BINSTAR_TOKEN: ZTfzo0qd41FDSTpHjCtBEHNsFNCR4+OPo6rJJjBeq3BEvIXOgNS3kKxkpz6GFDSGoeCIT8t4/ubwlmXwcTdJqTckt3GdefwVma+k4A164is7f/jf+Ydfk8G3QiXCTtfp+KV7G4tCfx/ftuUMTLUSxt1oq7UyZRS5aKh6eEq5OWJnVGT6plF5BZB02R8neEGCAgwX+z6pxBNRl+KZrBt5hUBrtqxzrtVhxPZRiGQehb9XhvhCfWfWBtvtO8bcGEKW96kERB+904H2ENuYKTqf+6+k3xjGxf4hzuZLyD0hViODYTntp0Wdbqng+DGQh2HXlOQP9nKq8E3aQ2hUPTSoc1VwEdGSjGdtyBr/PJ39SrML6yuJpHassubd96AnMJo7dG9/uxBU68z7VM3bmhP8ZegNPC4F8dwly+jXnYNSS72kha3W0FVp69ZEz1GAnNivuk+yHhWbLMnabNVHW0ElbqJNDF5Xy9pgZ7kX/Cs0r0Vq6RwTs/+1jhVPufnmPIRQEGXxv2ULaLXDaF0MD+DNO9iZWaPt9dpA0c8jINATxNgCK/r9a3O4jrdLyTVLLEMy72pD2XWEHZAhqdiibBVbYhq/JVUopxXsYt0sMQ3v9toTlVWpJSv3kuKZbskrZ1QtSXhVdg4EmICFcK25GwqivcWffgxFL3EtopvLlu7kHMo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
